/* automatically generated by rust-bindgen 0.59.1 */

pub const INIT_SUCCEDED: ::std::os::raw::c_int = 0;
pub const INIT_INVALID_UPPER_BOUND: ::std::os::raw::c_int = -1;
pub const GENERATING_SUCCEDED: ::std::os::raw::c_int = 0;
pub const GENERATING_FAILED: ::std::os::raw::c_int = -1;
pub const GENERATING_PARAMETERS_ARE_NOT_VALID: ::std::os::raw::c_int = -2;
extern "C" {
    #[link_name = "\u{1}_Z35InitializeNaturalSequenceParametersPPvj"]
    pub fn InitializeNaturalSequenceParameters(
        parameters_container_to_initialize: *mut *mut ::std::os::raw::c_void,
        upper_bound: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    #[link_name = "\u{1}_Z23GenerateNaturalSequencePvPS_"]
    pub fn GenerateNaturalSequence(
        parameters_container: *mut ::std::os::raw::c_void,
        generated_sequence_container: *mut *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
